export const SAVE_BANNER_REQUEST = "SAVE_BANNER_REQUEST";
export const FETCH_BANNER_REQUEST = "FETCH_BANNER_REQUEST";
export const UPDATE_BANNER_REQUEST = "UPDATE_BANNER_REQUEST";
export const DELETE_BANNER_REQUEST = "DELETE_BANNER_REQUEST";
export const BANNER_SUCCESS = "BANNER_SUCCESS";
export const BANNER_FAILURE = "BANNER_FAILURE";

export const FETCH_LANGUAGES_REQUEST = "FETCH_LANGUAGES_REQUEST";
export const LANGUAGES_SUCCESS = "LANGUAGES_SUCCESS";
export const LANGUAGES_FAILURE = "LANGUAGES_FAILURE";

export const FETCH_GENRES_REQUEST = "FETCH_GENRES_REQUEST";
export const GENRES_SUCCESS = "GENRES_SUCCESS";
export const GENRES_FAILURE = "GENRES_FAILURE";
